# [build]
# rustflags = ["-C", "link-arg=-ObjC"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-ObjC"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
